import {useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import games from './games.json';
const repo='https://github.com/Vetri1706/matchaboy';
export function Arcade(){
 const rail=useRef<HTMLDivElement>(null),drag=useRef<{x:number;scroll:number;last:number;velocity:number;time:number;moved:boolean}|null>(null),[position,setPosition]=useState(0),[firstVisible,setFirstVisible]=useState(1),[error,setError]=useState<string[]>([]);
 const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const advance=(direction:number)=>{const el=rail.current;if(!el)return;gsap.to(el,{scrollLeft:Math.max(0,Math.min(el.scrollWidth-el.clientWidth,el.scrollLeft+direction*el.clientWidth*.72)),duration:reduced()?0:.65,ease:'power3.inOut'});};
 useEffect(()=>()=>{if(rail.current)gsap.killTweensOf(rail.current);},[]);
 return <section className="arcade-section" id="arcade">
  <div className="section-heading"><p className="eyebrow">YOUR NEXT LITTLE OBSESSION</p><h2>Good games.<br/>Ready when you are.</h2><p>The app comes with two independent favourites.<br/>Unzip, choose a game, and find your rhythm.</p></div>
  <div className="included-games">{[{id:'tobu-tobu-girl',title:'Tobu Tobu Girl',note:'Bounce, dash and boost through the sky to rescue your floating cat.'},{id:'tobu-tobu-girl-deluxe',title:'Tobu Tobu Girl Deluxe',note:'A larger adventure, running here in Game Boy compatibility mode.'}].map((g,i)=><article key={g.id}><div className="included-image"><img src={'/captures/'+g.id+'.png'} alt={g.title+' running in Matchaboy'} width="1280" height="920" loading="lazy"/></div><div><span className="eyebrow">INCLUDED / GAME BOY</span><h3>{g.title}</h3><p>{g.note}</p><small>Tangram Games · Music by potato-tan</small><a href="#download" className="text-button">Get the app ↗</a></div></article>)}</div>
  <div className="game-credit"><span>Unmodified official ROMs · Code MIT · Assets CC BY 4.0</span><a href="/captures/CREDITS.txt" target="_blank" rel="noreferrer">Full game credits ↗</a></div>
  <div className="workshop-heading"><div><p className="eyebrow">FROM THE WORKSHOP</p><h3>Ten small experiments.<br/>Plenty to discover.</h3><p>Original GB and GBA games built with Astra. Available in the source as test cartridges; these are separate from the two games included in v0.1.1.</p></div><div className="carousel-controls"><span>{String(firstVisible).padStart(2,'0')} / 10</span><button className="round-button" aria-label="Previous games" disabled={position<=.005} onClick={()=>advance(-1)}>←</button><button className="round-button" aria-label="Next games" disabled={position>=.995} onClick={()=>advance(1)}>→</button></div></div>
  <div className="cartridge-run" ref={rail} tabIndex={0} aria-label="Original game workshop. Drag or use the arrow buttons." data-cursor="Drag" onScroll={()=>{const e=rail.current;if(e){setPosition(e.scrollLeft/Math.max(1,e.scrollWidth-e.clientWidth));const card=e.firstElementChild as HTMLElement|null;const step=(card?.offsetWidth??260)+parseFloat(getComputedStyle(e).gap);setFirstVisible(Math.min(games.length,Math.floor(e.scrollLeft/step)+1));}}} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();advance(e.key==='ArrowRight'?1:-1);}}}
   onPointerDown={e=>{if(e.pointerType!=='mouse'||e.button!==0)return;const el=e.currentTarget;gsap.killTweensOf(el);drag.current={x:e.clientX,scroll:el.scrollLeft,last:e.clientX,velocity:0,time:performance.now(),moved:false};}}
   onPointerMove={e=>{if(!drag.current)return;const d=drag.current,now=performance.now();if(Math.abs(e.clientX-d.x)>5){d.moved=true;e.currentTarget.setPointerCapture(e.pointerId);}d.velocity=(e.clientX-d.last)/Math.max(1,now-d.time);d.time=now;d.last=e.clientX;if(d.moved)e.currentTarget.scrollLeft=d.scroll-(e.clientX-d.x);}}
   onPointerUp={e=>{const d=drag.current;if(d?.moved){e.currentTarget.releasePointerCapture(e.pointerId);const el=e.currentTarget;gsap.to(el,{scrollLeft:Math.max(0,Math.min(el.scrollWidth-el.clientWidth,el.scrollLeft-d.velocity*190)),duration:reduced()?0:.7,ease:'power3.out'});}setTimeout(()=>{drag.current=null;},0);}}
   onPointerCancel={()=>{drag.current=null;}} onClickCapture={e=>{if(drag.current?.moved){e.preventDefault();e.stopPropagation();}}}>
   {games.map((g,i)=><article key={g.id} className="cartridge" onPointerMove={e=>{if(drag.current?.moved||reduced()||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--tilt',((e.clientX-r.left)/r.width-.5)*6+'deg');}} onPointerLeave={e=>e.currentTarget.style.setProperty('--tilt','0deg')}>
    <div className="cartridge-top"><span>{g.system}</span><b>{String(i+1).padStart(2,'0')}</b></div>
    <div className={'game-poster '+(g.native?'native-crop':'')}>{error.includes(g.id)?<p>Preview unavailable<br/><a href={repo+'/tree/feature/original-arcade/games'}>View game source ↗</a></p>:<img draggable={false} src={g.image} alt={g.title+' gameplay capture'} loading="lazy" onError={()=>setError(v=>[...v,g.id])}/>}</div>
    <h4>{g.title}</h4><p>{g.goal}</p><a href={repo+'/blob/feature/original-arcade/'+g.source} target="_blank" rel="noreferrer" data-cursor="Open">Explore the source <span>↗</span></a>
   </article>)}
  </div><div className="carousel-foot"><span>Drag to discover / 5 Game Boy + 5 Game Boy Advance</span><div className="rail-progress"><i style={{transform:'translateX('+position*300+'%)'}}/></div><a href={repo+'/blob/feature/original-arcade/games/PROVENANCE.md'} target="_blank" rel="noreferrer">Artwork, code & credits ↗</a></div>
 </section>;
}
