"""Generate the checked-in native catalog from the original games' manifests."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
ORDER=['pocket-racer','moon-courier','matcha-garden','signal-lost','orbit-guard',
       'drift-circuit','cloud-pilot','prism-break','tiny-tactics','parcel-dash']
GENRES=['Racing','Platformer','Puzzle','Exploration','Arcade defence',
        'Time trial','Flight','Brick breaker','Strategy','Score attack']

def catalog():
    games={}
    for system in ['gb','gba']:
        for game in json.loads((ROOT/'games'/system/'manifest.json').read_text())['games']:
            if game['id'] in games:raise ValueError('Duplicate game ID')
            games[game['id']]=game
    if set(games)!=set(ORDER):raise ValueError('Arcade must contain the ten named games')
    lines=['// Generated by tools/update_arcade_catalog.py; original-game metadata.',
           'constexpr std::array<ArcadeGame,10> catalog{{']
    for i,game_id in enumerate(ORDER):
        game=games[game_id]
        path=ROOT/game['rom']
        if not path.is_file():raise ValueError('Missing ROM: '+game['rom'])
        if game.get('sha256') and hashlib.sha256(path.read_bytes()).hexdigest()!=game['sha256']:
            raise ValueError('ROM hash mismatch: '+game_id)
        fields=[game_id,game['title'],game['system'],GENRES[i],game['goal'],game['controls'],
                game['learn'],game['inspector_hint'],game['source']]
        lines.append('    {'+', '.join(json.dumps(x,ensure_ascii=True) for x in fields)+'},')
    lines.append('}};')
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    target=ROOT/'include/arcade_catalog.inc';expected=catalog()
    if a.check:
        if not target.exists() or target.read_text()!=expected:raise SystemExit('Arcade catalog is stale; regenerate it.')
        print('Ten ROMs and native catalog verified.')
    else:
        target.write_text(expected,encoding='utf-8');print(target)
