"""Validate licensed homebrew and generate the native catalog/resource lists."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'games/homebrew/manifest.json'
FIELDS = ('id', 'title', 'system', 'genre', 'description', 'controls', 'learn',
          'inspector_hint', 'source', 'author', 'license', 'players', 'rom_filename')


def catalog():
    manifest = json.loads(MANIFEST.read_text(encoding='utf-8'))
    games = manifest['games']
    if manifest['schema'] != 1 or not 1 <= len(games) <= 10:
        raise ValueError('Expected schema 1 and 1..10 homebrew titles')
    ids, files = set(), set()
    for game in games:
        for field in FIELDS:
            value = game[field]
            if not isinstance(value, str) or not value or any(ord(c) < 32 for c in value):
                raise ValueError(f'{field} must be nonempty single-line text')
        ident = game['id']
        if not re.fullmatch('[a-z0-9]+(?:-[a-z0-9]+)*', ident) or ident in ids:
            raise ValueError('Invalid or duplicate ID: ' + ident)
        ids.add(ident)
        extension = {'GB': '.gb', 'GBA': '.gba'}.get(game['system'])
        filename = game['rom_filename']
        if not extension or filename != ident + extension or filename in files:
            raise ValueError('Invalid, unsupported or duplicate ROM filename: ' + filename)
        files.add(filename)
        expected_path = 'games/homebrew/roms/' + filename
        if game['rom'] != expected_path:
            raise ValueError('ROM path must identify its declared bundled filename')
        data = (ROOT / expected_path).read_bytes()
        if len(data) != game['bytes'] or hashlib.sha256(data).hexdigest() != game['sha256']:
            raise ValueError('ROM hash/size mismatch: ' + ident)
        if extension == '.gb' and (len(data) < 0x150 or data[0x143] == 0xC0):
            raise ValueError('Bundled GB game requires unsupported Color-only hardware')
        if not game['source'].startswith('https://') or not game['upstream_repository'].startswith('https://'):
            raise ValueError('Official project URLs must use HTTPS')
        for suffix in ('-LICENSE.txt', '-UPSTREAM.md'):
            if not (ROOT / 'games/homebrew/licenses' / (ident + suffix)).is_file():
                raise ValueError('Missing upstream license/asset grant: ' + ident)
        test = game['test']
        if not (0 < test['boot_frames'] <= 10000 and 0 < test['input_frames'] <= 600 and
                0 < test['input_mask'] <= (255 if extension == '.gb' else 1023)):
            raise ValueError('Invalid bounded controller test recipe: ' + ident)
    # Fail on stale additions too: players must not silently package extra ROMs.
    if {p.name for p in (ROOT / 'games/homebrew/roms').iterdir()} != files:
        raise ValueError('Bundled ROM directory differs from the licensed manifest')
    lines = ['// Generated by tools/update_arcade_catalog.py; licensed homebrew metadata.',
             f'constexpr std::array<ArcadeGame,{len(games)}> catalog{{{{']
    for game in games:
        lines.append('    {' + ', '.join(json.dumps(game[f], ensure_ascii=True) for f in FIELDS) + '},')
    lines.append('}};')
    resources = ['// Generated by tools/update_arcade_catalog.py; manifest order matches catalog.']
    cmake = ['# Generated by tools/update_arcade_catalog.py.', 'set(MATCHA_ARCADE_ROMS']
    for index, game in enumerate(games):
        resources.append(f'{201 + index} RCDATA "@PROJECT_SOURCE_DIR@/{game["rom"]}"')
        cmake.append(f'    "${{PROJECT_SOURCE_DIR}}/{game["rom"]}"')
    cmake.append(')')
    resources.append('300 RCDATA "@PROJECT_SOURCE_DIR@/games/homebrew/CREDITS.txt"')
    return {ROOT / 'include/arcade_catalog.inc': '\n'.join(lines) + '\n',
            ROOT / 'assets/arcade.rc.in': '\n'.join(resources) + '\n',
            ROOT / 'cmake/Homebrew.cmake': '\n'.join(cmake) + '\n'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for target, expected in catalog().items():
        if args.check:
            if not target.is_file() or target.read_text(encoding='utf-8') != expected:
                raise SystemExit('Homebrew catalog/resources are stale; regenerate them: ' + str(target))
        else:
            target.write_text(expected, encoding='utf-8')
    print('Homebrew ROM hashes, licenses and native resources verified.')
