# Generated by tools/update_arcade_catalog.py.
set(MATCHA_ARCADE_ROMS
    "${PROJECT_SOURCE_DIR}/games/homebrew/roms/tobu-tobu-girl.gb"
    "${PROJECT_SOURCE_DIR}/games/homebrew/roms/tobu-tobu-girl-deluxe.gb"
)
