/* SPDX-License-Identifier: GPL-3.0-only
 * Original Matchaboy Arcade work, generated by the assistant under user direction.
 * No external artwork, fonts, music, levels or game framework are used.
 */
#ifndef MATCHA_ARCADE_H
#define MATCHA_ARCADE_H
enum { K_A=1, K_B=2, K_SELECT=4, K_START=8, K_RIGHT=16, K_LEFT=32, K_UP=64, K_DOWN=128 };
enum { TITLE, PLAY, WON, LOST };
enum { DRIFT, CLOUD, PRISM, TACTICS, PARCEL };
typedef struct { int x,y,vx,vy,alive,hp; } Object;
typedef struct {
    int kind, phase, frame, tick, score, time, hp, x, y, vx, vy;
    int prev, pressed, sound, cooldown, stage, target, carrying, moves;
    int bricks[24];
    Object obj[12];
} Game;
#ifdef HOST_TEST
#define API __declspec(dllexport)
#else
#define API
#endif
API void game_init(Game *g, int kind);
API void game_step(Game *g, int keys);
API int road_center(int tick);
API int parcel_target_x(int index);
API int parcel_target_y(int index);
API int tactics_wall(int x, int y);
void draw_game(const Game *g);
#endif
